name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main  # Change this to your default branch (e.g., master, main)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Use OpenJDK distribution (Temurin)
          java-version: '21'       # Set the JDK version to 21
          cache: 'maven'           # Cache Maven dependencies
          cache-dependency-path: 'pom.xml'  # Optional, path to the main pom.xml for caching

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Build the app using Maven

      - name: Run tests with Maven
        run: mvn clean test  # Run Maven tests

      - name: Build Docker image
        if: success()
        run: |
          echo "Building Docker image with tag: ${{ secrets.DOCKER_USERNAME }}/springboot-ci-cd:${{ github.sha }}"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-ci-cd:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
            IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/springboot-ci-cd"
            TAG="${{ github.sha }}"
            docker build -t $IMAGE_NAME:$TAG .

      - name: Push Docker Image to Docker Hub
        run: |
            IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/springboot-ci-cd"
            TAG="${{ github.sha }}"
            docker push $IMAGE_NAME:$TAG