name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main  # Change this to your default branch (e.g., master, main)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Use OpenJDK distribution (Temurin)
          java-version: '21'       # Set the JDK version to 21
          cache: 'maven'           # Cache Maven dependencies
          cache-dependency-path: 'pom.xml'  # Optional, path to the main pom.xml for caching

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Build the app using Maven

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
            images: |
                    my-docker-hub-namespace/my-docker-hub-repository
                    ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
            subject-name: ghcr.io/${{ github.repository }}
            subject-digest: ${{ steps.push.outputs.digest }}
            push-to-registry: true