name: Build and Deploy Spring Boot Application

on:
  push:
    branches:
      - main  # Change this to your default branch (e.g., master, main)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Use OpenJDK distribution (Temurin)
          java-version: '21'       # Set the JDK version to 21
          cache: 'maven'           # Cache Maven dependencies
          cache-dependency-path: 'pom.xml'  # Optional, path to the main pom.xml for caching

      - name: Build with Maven
        run: mvn -B package --file pom.xml  # Build the app using Maven

      - name: Verify Docker Username
        run: |
            if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME is empty!"
            exit 1
            fi

      - name: Login to Docker Hub
        id: docker-hub
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u "$username" -p "$password"

      - name: Build the Docker Image
        id: build-docker-image
        run: |
          ls -la 
          docker build . -f Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-ci-cd:latest

      - name: Push the Docker Image
        id: push-docker-image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-ci-cd:latest