name: Build and Deploy Spring Boot Application to Docker Hub

on:
  push:
    branches:
      - main  # Change this to your default branch (e.g., master, main)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Use JDK 21 for Spring Boot
          java-package: 'jdk'  # Full JDK package

      - name: Run tests with Maven
        run: mvn clean test  # Run Maven tests

      - name: Build Docker image
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-ci-cd:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/springboot-ci-cd:${{ github.sha }}
